#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper in Hyprland

WALLPAPER="$HOME/.config/hypr/wallpapers/programmer.gif"
swww-daemon & 
swww img $WALLPAPER
